[package]
name = "wasmedge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# , features = ["aot"] 
[dependencies]
wasmedge-sdk = { version = "0.13.2", features = ["aot"] }
# wasmedge-types = { version = "0.5.0" }
